name: null
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.0.1
  - python=3.8.12
  - setuptools=58.0.4
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - pip:
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - charset-normalizer==2.0.7
    - idna==3.3
    - lxml==4.6.4
    - multitasking==0.0.9
    - numpy==1.21.4
    - pandas==1.3.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.26.0
    - six==1.16.0
    - soupsieve==2.3.1
    - urllib3==1.26.7
    - yfinance==0.1.64
